services:
  simplescriptwebsite:
    image: simplescriptwebsite
    build:
      context: .
      dockerfile: SimpleScriptWebSite/Dockerfile
    ports:
      - "10000:8080"
    environment:
      DOCKER_HOST: "tcp://docker:2375"
      #- DOCKER_HOST=https://docker:2376
      #- DOCKER_TLS_VERIFY=1
      #- DOCKER_CERT_PATH=/certs/client
    depends_on:
      - docker
    #volumes:
      #- /home/tim/Source/projects/SimpleScriptWebSite/ConsoleApp:/ConsoleApp
    #  - docker-certs:/certs/client:ro

  docker:
    image: docker:dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
      DOCKERD_OPTS: "-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock --tlsverify=false"
      #DOCKER_TLS_CERTDIR: "/certs/client"
    ports:
      - "2375:2375"
      #- "2376:2376"
    volumes:
      - docker-data:/var/lib/docker
      # TODO Hier sollte ein Host unabhängiger Pfad stehen!
      - /home/tim/Source/projects/SimpleScriptWebSite/ConsoleApp:/ConsoleApp
      #- docker-certs:/certs/client

volumes:
  docker-certs:
  docker-data: