services:
  simplescriptwebsite:
    image: simplescriptwebsite
    build:
      context: .
      dockerfile: SimpleScriptWebSite/Dockerfile
    ports:
      - "10000:8080"
    environment:
      DOCKER_HOST: "https://docker:2376"
      DOCKER_TLS_VERIFY: "1"
      DOCKER_CERT_PATH: "/certs/client"
      SSL_CERT_DIR: "/etc/ssl/certs"
      SSL_CERT_FILE: "/etc/ssl/certs/ca-certificates.crt"
    depends_on:
      - docker
    volumes:
      - ./certs/client/client.pem:/certs/client/cert.pem:ro
      - ./certs/client/client-key.pem:/certs/client/key.pem:ro
      - ./Dockerfiles/Dockerfile:/Dockerfile:ro

  docker:
    build:
      context: .
      dockerfile: docker-dind.Dockerfile
    privileged: true
    ports:
      - "2376:2376"
    # Override the default command to prevent conflicting flags with daemon.json
    command: [ "dockerd" ]
    volumes:
      - docker-data:/var/lib/docker
      - ./certs/server/server.pem:/certs/server/cert.pem:ro
      - ./certs/server/server-key.pem:/certs/server/key.pem:ro
      - ./certs/ca.pem:/certs/server/ca.pem:ro
      - ./daemon.json:/etc/docker/daemon.json:ro

volumes:
  docker-data: