services:
  simplescriptwebsite:
    image: simplescriptwebsite
    build:
      context: .
      dockerfile: SimpleScriptWebSite/Dockerfile
    user: root
    ports:
      - "10000:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock